In [1]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Load the traffic dataset

file_path = "PeMSD7_V_228.csv"
data = pd.read_csv(file_path, header=None)
print("Dataset loaded successfully!")

Dataset loaded successfully!

In [3]:
# Create meaningful column names for the 228 traffic sensors

data.columns = [f"Sensor_{i+1}" for i in range(data.shape[1])]
print("Column names assigned successfully!")

Column names assigned successfully!

In [4]:
# Dataset Exploration

print("Number of observations:", data.shape[0])

print("Number of attributes:", data.shape[1])

Number of observations: 12672
Number of attributes: 228

In [5]:
# Display the first 5 rows of the dataset

data.head()

,Sensor_1,Sensor_2,Sensor_3,Sensor_4,Sensor_5,Sensor_6,Sensor_7,Sensor_8,Sensor_9,Sensor_10,...,Sensor_219,Sensor_220,Sensor_221,Sensor_222,Sensor_223,Sensor_224,Sensor_225,Sensor_226,Sensor_227,Sensor_228
0,71.1,66.0,64.6,65.6,67.1,71.9,68.6,67.7,65.8,40.9,...,69.1,70.9,65.0,64.5,66.6,66.6,65.0,69.3,67.7,68.9
1,68.1,66.8,61.7,66.7,64.5,71.6,72.3,64.9,65.6,40.1,...,70.6,65.4,65.0,64.9,65.1,67.7,65.0,67.7,68.8,68.8
2,68.0,64.3,66.6,68.7,68.1,70.5,70.2,61.7,63.4,39.6,...,72.2,70.5,65.0,64.7,66.7,68.9,65.0,70.2,69.1,68.7
3,68.3,67.8,65.9,66.6,67.9,70.3,69.8,67.6,63.2,37.6,...,71.2,69.7,65.0,65.2,67.2,66.9,65.0,70.4,67.3,69.0
4,68.9,69.5,61.2,67.4,64.0,68.1,67.0,66.7,64.2,36.8,...,71.3,65.8,65.0,66.3,66.7,66.2,65.0,68.0,67.4,68.1

In [6]:
# Check for missing values in the dataset
print("Total missing values:", data.isnull().sum().sum())

Total missing values: 0

In [7]:
# Check for duplicate rows
print("Duplicate rows:", data.duplicated().sum())

Duplicate rows: 0

In [8]:
# Display basic information about the dataset

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12672 entries, 0 to 12671
Columns: 228 entries, Sensor_1 to Sensor_228
dtypes: float64(228)
memory usage: 22.0 MB

In [1]:

# FEATURE ENGINEERING
data["Average_Traffic"] = data.iloc[:, :228].mean(axis=1)

# Display the first 5 values
data["Average_Traffic"].head()

NameError: name 'data' is not defined

In [2]:

import pandas as pd

file_path = "PeMSD7_V_228.csv"

data = pd.read_csv(file_path, header=None)
data.columns = [f"Sensor_{i+1}" for i in range(data.shape[1])]

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [3]:

# FEATURE ENGINEERING


data["Average_Traffic"] = data.iloc[:, :228].mean(axis=1)

# Display the first 5 values
data["Average_Traffic"].head()

0    67.541228
1    67.479386
2    67.413158
3    67.305263
4    66.953070
Name: Average_Traffic, dtype: float64

In [4]:
# Display the first 5 rows of the new feature

print("Average traffic feature created successfully!")

data[["Average_Traffic"]].head()

Average traffic feature created successfully!

   Average_Traffic
0        67.541228
1        67.479386
2        67.413158
3        67.305263
4        66.953070

In [5]:
     # Explore the newly created Average_Traffic feature

print("Minimum:", data["Average_Traffic"].min())
print("Maximum:", data["Average_Traffic"].max())
print("Mean:", data["Average_Traffic"].mean())
print("Median:", data["Average_Traffic"].median())

Minimum: 35.640350877193
Maximum: 69.78377192982458
Mean: 58.88918398624402
Median: 59.547807017543846

In [6]:
# Create congestion level thresholds

low_threshold = data["Average_Traffic"].quantile(0.33)
high_threshold = data["Average_Traffic"].quantile(0.67)

print("Low threshold:", low_threshold)
print("High threshold:", high_threshold)

Low threshold: 56.010026315789474
High threshold: 65.83201754385965

In [7]:
# Create the Congestion Level target variable

data["Congestion_Level"] = pd.cut(
    data["Average_Traffic"],
    bins=[-np.inf, low_threshold, high_threshold, np.inf],
    labels=["Low", "Medium", "High"]
)

# Display the first 10 congestion levels
data[["Average_Traffic", "Congestion_Level"]].head(10)

NameError: name 'np' is not defined

In [8]:
# Import NumPy

import numpy as np